id: P2E4EAF20
initial_creation_type: input
source_metadata:
  Title: Sarva Tathāgata Tattva Saṅgraha
  Editor: Chandra, Lokesh
  Publisher: Motilal Banarsidas
  Place of Publication: Delhi
  Year: '1987'
  Prathamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvitīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Tṛtīyaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturthaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaṣṭhamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Navamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Daśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ekādaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvādaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Trayodaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturdaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcadaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣoḍaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Saptadaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Aṣṭādaśamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ekānnaviṃśatimaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Viṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ekaviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Dvāviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Trayoviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Caturviṃśatitamaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Pañcaviṃśatimaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
  Ṣaḍviṃśatimaḥ:
    Text Version: Romanized
    Input Personnel: DSBC Staff
    Input Date: '2008'
    Proof Reader: Miroj Shakya
    Supplier: Nagarjuna Institute of Exact Methods
    Sponsor: University of the West
created_at: '2022-03-08T16:15:07.714644'
last_modified_at: '2022-03-08T16:15:07.714656'
